#
# Try to find D3D8 library and include path.
# Once done this will define
#
# D3D8_FOUND
# D3D8_INCLUDE_PATH
# D3D8_LIBRARY
# D3DX8_FOUND
# D3DX8_INCLUDE_PATH
# D3DX8_LIBRARY
# 

IF (WIN32)
  if (NOT CMAKE_CL_64)
	FIND_PATH( D3D8_INCLUDE_PATH d3d8.h
		HINTS
		$ENV{LIBRARYDIR}
		PATH_SUFFIXES include
		PATHS
		$ENV{LIBRARYDIR}/DXSDK/include
		$ENV{LIBRARYDIR}/dx81sdk/include
		DOC "The directory where d3d8.h resides")
	FIND_PATH( D3DX8_INCLUDE_PATH d3dx8.h
		HINTS
		$ENV{LIBRARYDIR}
		PATH_SUFFIXES include
		PATHS
		$ENV{LIBRARYDIR}/DXSDK/include
		$ENV{LIBRARYDIR}/dx81sdk/include
		DOC "The directory where d3dx8.h resides")
	FIND_LIBRARY( D3D8_LIBRARY
		NAMES d3d8
		HINTS
		$ENV{LIBRARYDIR}
		PATH_SUFFIXES lib
		PATHS
		$ENV{LIBRARYDIR}/DXSDK/lib
		$ENV{LIBRARYDIR}/dx81sdk/lib
		DOC "Direct3D8 library")
	FIND_LIBRARY( D3DX8_LIBRARY
		NAMES d3dx8
		HINTS
		$ENV{LIBRARYDIR}
		PATH_SUFFIXES lib
		PATHS
		$ENV{LIBRARYDIR}/DXSDK/lib
		$ENV{LIBRARYDIR}/dx81sdk/lib
		DOC "Direct3DX8 library")
  else (NOT CMAKE_CL_64)
	MESSAGE("64-bit version of Direct3D 8 is not available.")
  endif (NOT CMAKE_CL_64)
ELSE (WIN32)
  MESSAGE("Direct3D 8 is not available on this platform.")
ENDIF (WIN32)

IF (D3D8_INCLUDE_PATH)
	SET(D3D8_FOUND TRUE)
ELSE (D3D8_INCLUDE_PATH)
	SET(D3D8_FOUND FALSE)
ENDIF (D3D8_INCLUDE_PATH)

IF (D3DX8_INCLUDE_PATH)
	SET(D3DX8_FOUND TRUE)
ELSE (D3DX8_INCLUDE_PATH)
	SET(D3DX8_FOUND FALSE)
ENDIF (D3DX8_INCLUDE_PATH)

IF(D3D8_FIND_REQUIRED)
  IF(NOT D3D8_FOUND)
    MESSAGE(FATAL_ERROR "Direct3D8 not found")
  ENDIF(NOT D3D8_FOUND)
ENDIF(D3D8_FIND_REQUIRED)

IF(D3D8_FIND_REQUIRED)
  IF(NOT D3DX8_FOUND)
    MESSAGE(FATAL_ERROR "Direct3DX8 not found")
  ENDIF(NOT D3DX8_FOUND)
ENDIF(D3D8_FIND_REQUIRED)

MARK_AS_ADVANCED( D3D8_FOUND )
